// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Group struct {
	ID   int64
	Name string
}

type Product struct {
	ID               int64
	Name             string
	GroupID          interface{}
	IconKey          string
	QuantityValue    float64
	QuantityUnit     string
	MinQuantityValue float64
	Missing          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ProductIconRule struct {
	ID             int64
	MatchSubstring string
	IconKey        string
	Priority       int64
}

type ShoppingListItem struct {
	ID            int64
	ProductID     sql.NullInt64
	Name          string
	QuantityValue float64
	QuantityUnit  string
	Done          int64
	CreatedAt     time.Time
}

type VGroup struct {
	ID   int64
	Name string
}

type VProduct struct {
	ID               int64
	Name             string
	IconKey          string
	GroupID          interface{}
	GroupName        sql.NullString
	QuantityValue    float64
	QuantityUnit     string
	MinQuantityValue float64
	Missing          int64
	UpdatedAt        time.Time
}
