// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Group struct {
	ID   int64
	Name string
}

type CreateProductParams struct {
	Name    string
	GroupID sql.NullInt64
}

type SetProductGroupParams struct {
	GroupID sql.NullInt64
	ID      int64
}

type ListProductsAllRow struct {
	ID          int64
	Name        string
	GroupID     sql.NullInt64
	GroupName   sql.NullString
	Quantity    int64
	MinQuantity int64
	Missing     int64
	UpdatedAt   time.Time
}

type ListProductsMissingOrLowRow struct {
	ID          int64
	Name        string
	GroupID     sql.NullInt64
	GroupName   sql.NullString
	Quantity    int64
	MinQuantity int64
	Missing     int64
	UpdatedAt   time.Time
}

type SetProductMinQuantityParams struct {
	MinQuantity int64
	ID          int64
}

type SetProductMissingParams struct {
	Missing int64
	ID      int64
}

type SetProductQuantityParams struct {
	Quantity int64
	ID       int64
}
