// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

const listGroups = `-- name: ListGroups :many
SELECT id, name
FROM v_groups
ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups(name) VALUES (?)
RETURNING id
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listProductsAll = `-- name: ListProductsAll :many
SELECT
  p.id,
  p.name,
  p.group_id,
  p.group_name,
  p.quantity,
  p.min_quantity,
  p.missing,
  p.updated_at
FROM v_products p
ORDER BY p.name
`

func (q *Queries) ListProductsAll(ctx context.Context) ([]ListProductsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsAllRow
	for rows.Next() {
		var i ListProductsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.GroupName,
			&i.Quantity,
			&i.MinQuantity,
			&i.Missing,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsMissingOrLow = `-- name: ListProductsMissingOrLow :many
SELECT
  p.id,
  p.name,
  p.group_id,
  p.group_name,
  p.quantity,
  p.min_quantity,
  p.missing,
  p.updated_at
FROM v_products p
WHERE p.missing = 1 OR p.quantity <= p.min_quantity
ORDER BY p.name
`

func (q *Queries) ListProductsMissingOrLow(ctx context.Context) ([]ListProductsMissingOrLowRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsMissingOrLow)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsMissingOrLowRow
	for rows.Next() {
		var i ListProductsMissingOrLowRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.GroupName,
			&i.Quantity,
			&i.MinQuantity,
			&i.Missing,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(name, group_id, quantity, min_quantity, missing, created_at, updated_at)
VALUES (?, ?, 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id
`

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Name, nullInt64ToAny(arg.GroupID))
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setProductQuantity = `-- name: SetProductQuantity :exec
UPDATE products
SET quantity = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SetProductQuantity(ctx context.Context, arg SetProductQuantityParams) error {
	_, err := q.db.ExecContext(ctx, setProductQuantity, arg.Quantity, arg.ID)
	return err
}

const setProductMinQuantity = `-- name: SetProductMinQuantity :exec
UPDATE products
SET min_quantity = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SetProductMinQuantity(ctx context.Context, arg SetProductMinQuantityParams) error {
	_, err := q.db.ExecContext(ctx, setProductMinQuantity, arg.MinQuantity, arg.ID)
	return err
}

const setProductMissing = `-- name: SetProductMissing :exec
UPDATE products
SET missing = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SetProductMissing(ctx context.Context, arg SetProductMissingParams) error {
	_, err := q.db.ExecContext(ctx, setProductMissing, arg.Missing, arg.ID)
	return err
}

const setProductGroup = `-- name: SetProductGroup :exec
UPDATE products
SET group_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SetProductGroup(ctx context.Context, arg SetProductGroupParams) error {
	_, err := q.db.ExecContext(ctx, setProductGroup, nullInt64ToAny(arg.GroupID), arg.ID)
	return err
}

const pragmaOptimize = `-- name: PragmaOptimize :exec
PRAGMA optimize
`

func (q *Queries) PragmaOptimize(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, pragmaOptimize)
	return err
}

func nullInt64ToAny(v sql.NullInt64) any {
	if v.Valid {
		return v.Int64
	}
	return nil
}
